/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import glucosabajocontrol.CuentaDP;
import glucosabajocontrol.PacienteDP;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Martin Guerra
 */
public class IngresodePacientes extends javax.swing.JDialog {

    /**
     * Creates new form IngresodePacientes
     */
    public IngresodePacientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setLocationRelativeTo(null);
        this.setTitle("Registro de nuevo paciente");
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_peso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tiposanguineo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_tipodiabetes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingreso de Pacientes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cédula:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        txt_cedula.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_cedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_cedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cedulaFocusLost(evt);
            }
        });
        jPanel1.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 210, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        txt_nombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 210, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        txt_apellido.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_apellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 210, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edad:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        txt_edad.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_edad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_edad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_edadFocusLost(evt);
            }
        });
        jPanel1.add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 210, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Altura:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txt_altura.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_altura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_altura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_alturaFocusLost(evt);
            }
        });
        jPanel1.add(txt_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 210, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Peso:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        txt_peso.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_peso.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_peso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_pesoFocusLost(evt);
            }
        });
        jPanel1.add(txt_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TipoSanguineo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        txt_tiposanguineo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_tiposanguineo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(txt_tiposanguineo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 210, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TipoDiabetes:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        txt_tipodiabetes.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txt_tipodiabetes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_tipodiabetes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tipodiabetesFocusLost(evt);
            }
        });
        jPanel1.add(txt_tipodiabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 210, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Clave:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String cedula = txt_cedula.getText();
        String nombre = txt_nombre.getText();
        String apellido = txt_apellido.getText();
        String edad3 = txt_edad.getText();
        String altura3 = txt_altura.getText();
        String peso3 = txt_peso.getText();
        String tipoSanguineo = txt_tiposanguineo.getText();
        String tipoDiabetes3 = txt_tipodiabetes.getText();
        String clave = jPasswordField1.getText();
        if(!"".equals(cedula) && !"".equals(nombre) && !"".equals(apellido) && !"".equals(edad3) && !"".equals(altura3) && !"".equals(peso3) && !"".equals(tipoSanguineo) && !"".equals(tipoDiabetes3) && !"".equals(clave)){
            int edad = Integer.parseInt(txt_edad.getText());
            float altura = Float.parseFloat(txt_altura.getText());
            float peso = Float.parseFloat(txt_peso.getText());
            int tipoDiabetes = Integer.parseInt(txt_tipodiabetes.getText());
            PacienteDP pa = new PacienteDP(cedula,nombre,apellido,edad,altura,peso,tipoSanguineo,tipoDiabetes,clave);
            try{
                if(pa.agregar()){
                    JOptionPane.showMessageDialog(null, "Se ingreso con éxito el paciente");
                }
                else 
                    JOptionPane.showMessageDialog(null, "ERROR CON LA BASE DE DATOS");
            }catch (IOException ex){
                Logger.getLogger(IngresodePacientes.class.getName()).log(Level.SEVERE, null, ex);
            }catch (SQLException ex){
                Logger.getLogger(IngresodePacientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        CuentaDP cuedp = new CuentaDP(cedula,clave);
        try {
            cuedp.ingresarcon();
        } catch (IOException ex) {
            Logger.getLogger(IngresodePacientes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(IngresodePacientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        Verificacion();
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void txt_cedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cedulaFocusLost
        // TODO add your handling code here:
        try{
            Integer.parseInt(txt_cedula.getText());
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Datos no permitidos, ingrese un valor numérico");
            txt_cedula.setText("");
        }
    }//GEN-LAST:event_txt_cedulaFocusLost

    private void txt_edadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_edadFocusLost
        // TODO add your handling code here:
        try{
            Integer.parseInt(txt_edad.getText());
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Datos no permitidos, ingrese un valor numérico");
            txt_edad.setText("");
        }
    }//GEN-LAST:event_txt_edadFocusLost

    private void txt_alturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_alturaFocusLost
        // TODO add your handling code here:
        try{
            Float.parseFloat(txt_altura.getText());
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Datos no permitidos, ingrese un valor numérico");
            txt_altura.setText("");
        }
    }//GEN-LAST:event_txt_alturaFocusLost

    private void txt_pesoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_pesoFocusLost
        // TODO add your handling code here:
        try{
            Float.parseFloat(txt_peso.getText());
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Datos no permitidos, ingrese un valor numérico");
            txt_peso.setText("");
        }
    }//GEN-LAST:event_txt_pesoFocusLost

    private void txt_tipodiabetesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tipodiabetesFocusLost
        // TODO add your handling code here:
        try{
            Integer.parseInt(txt_tipodiabetes.getText());
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Datos no permitidos, ingrese un valor numérico");
            txt_tipodiabetes.setText("");
        }
    }//GEN-LAST:event_txt_tipodiabetesFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresodePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresodePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresodePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresodePacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngresodePacientes dialog = new IngresodePacientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_peso;
    private javax.swing.JTextField txt_tipodiabetes;
    private javax.swing.JTextField txt_tiposanguineo;
    // End of variables declaration//GEN-END:variables
    public void Verificacion()
    {
        String cedula = txt_cedula.getText();
        String nombre = txt_nombre.getText();
        String apellido = txt_apellido.getText();
        String edad = txt_edad.getText();
        String altura = txt_altura.getText();
        String peso = txt_peso.getText();
        String tipoSanguineo = txt_tiposanguineo.getText();
        String tipoDiabetes = txt_tipodiabetes.getText();
        String clave = jPasswordField1.getText();
        
        if("".equals(cedula) && "".equals(nombre) && "".equals(apellido) && "".equals(edad) && "".equals(altura) && "".equals(peso) && "".equals(tipoSanguineo) && "".equals(tipoDiabetes) && "".equals(clave))
        {
            JOptionPane.showMessageDialog(null, "Por favor ingrese sus datos");
        }
        else if("".equals(cedula)){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su Cédula");
        }
        else if(cedula.length() < 10){
            JOptionPane.showMessageDialog(null, "La cédula debe tener una longitud de 10");
        }
        else if(cedula.length() > 10){
            JOptionPane.showMessageDialog(null, "La cédula no debe tener una longitud mayor a 10");
        }
        else if("".equals(nombre)){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su Nombre");
        }
        else if("".equals(apellido)){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su Apellido");
        }
        else if("".equals(edad)){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su Edad");
        }
        else if("".equals(altura)){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su Altura");
        }
        else if("".equals(peso)){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su Peso");
        }
        else if("".equals(tipoSanguineo)){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su Tipo de sangre");
        }
        else if("".equals(tipoDiabetes)){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su Tipo de diabetes");
        }
        else if("".equals(clave)){
            JOptionPane.showMessageDialog(null, "Por favor ingrese su contraseña");
        }
        else if(clave.length() < 4){
            JOptionPane.showMessageDialog(null, "La contraseña debe tener una longitud mayor a cuatro");
        }
        else
        {
            int edad2 = Integer.parseInt(txt_edad.getText());
            float altura2 = Float.parseFloat(txt_altura.getText());
            float peso2 = Float.parseFloat(txt_peso.getText());
            int tipoDiabetes2 = Integer.parseInt(txt_tipodiabetes.getText());
        }
    }
}
